baseURL = "https://jeromepin.fr"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Jérôme Pin"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "even"

pygmentsOptions = "linenos=table"
pygmentsStyle = "igor"
pygmentsCodefences = true
pygmentsUseClasses = false
pygmentsCodefencesGuessSyntax = true

[outputFormats]
  [outputFormats.SearchIndex]
    baseName = "search"
    mediaType = "application/json"

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[author]
  name = "Jérôme Pin"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  version = "4.x"
  since = "2017"
  logoTitle = ""
  keywords = [""]
  description = "Jérôme Pin - Site Reliability Engineer - Elasticsearch and Web performance enthusiast, Linux, Python. Love large-scale and distributed systems."
  archivePaginate = 5
  dateFormatToUse = "2 Jan"
  mathjax = true
  mathjaxEnableSingleDollar = false
  mathjaxEnableAutoNumber = false
  mathjaxUseLocalFiles = false
  customCSS = ['override.scss']
  customJS = ['cash.js', 'mermaid.js', 'lunr.stemmer.support.js', 'lunr.fr.js', 'search.js']

  [params.publicCDN]
    enable = false
    jquery = '<script src="https://cdnjs.cloudflare.com/ajax/libs/cash/4.1.5/cash.min.js"></script>'
    flowchartDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/raphael@2.2.7/raphael.min.js" integrity="sha256-67By+NpOtm9ka1R6xpUefeGOY8kWWHHRAKlvaTJ7ONI=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/flowchart.js@1.8.0/release/flowchart.min.js" integrity="sha256-zNGWjubXoY6rb5MnmpBNefO0RgoVYfle9p0tvOQM+6k=" crossorigin="anonymous"></script>'
    sequenceDiagramsCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.css" integrity="sha384-6QbLKJMz5dS3adWSeINZe74uSydBGFbnzaAYmp+tKyq60S7H2p6V7g1TysM5lAaF" crossorigin="anonymous">'
    sequenceDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js" integrity="sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/snapsvg@0.5.1/dist/snap.svg-min.js" integrity="sha256-oI+elz+sIm+jpn8F/qEspKoKveTc5uKeFHNNVexe6d8=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/underscore@1.8.3/underscore-min.js" integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.js" integrity="sha384-8748Vn52gHJYJI0XEuPB2QlPVNUkJlJn9tHqKec6J3q2r9l8fvRxrgn/E5ZHV0sP" crossorigin="anonymous"></script>'

  [params.flowchartDiagrams]
    enable = false
    options = ""

  [params.sequenceDiagrams]
    enable = false
    options = ""

  [params.social]
    b-stack-overflow = "https://stackoverflow.com/users/5515387"
    c-twitter = "https://twitter.com/jerome_pin"
    g-github = "https://github.com/jeromepin"
