title = "Jérôme Pin"

# The URL the site will be built for
base_url = "https://jeromepin.fr"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feed = true
author = "Jérôme Pin"

theme = "even"

taxonomies = [
    # You can enable/disable RSS
    # {name = "categories", feed = true},
    # {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
even_menu = []
katex_enable = true
katex_auto_render = true
entries = [
    {date = "2022-05-23T00:00:00+01:00", permalink = "https://medium.com/lumapps-engineering/terraform-at-lumapps-part-1-f37660b4ed95", title = "Terraform at LumApps: Part 1 - A huge Terraform monorepo", external = true},
    {date = "2023-12-18T00:00:00+01:00", permalink = "https://medium.com/lumapps-engineering/terraform-at-lumapps-part-2-27494897def4", title = "Terraform at LumApps: Part 2 - Managing terragrunt.hcl files at scale", external = true},
]