name: Push to GitHub Pages on push to master

on: push

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3.0.0

      - name: Deploy the site
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_PAGE }}
          PAGES_BRANCH: master
          REPOSITORY: jeromepin/jeromepin.github.io
