name: Push to GitHub Pages on push to master

on: push

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.0.0

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@v1.5.0
        env:
          HUGO_VERSION: 0.74.1
          HUGO_EXTENDED: true
          TARGET_REPO: jeromepin/jeromepin.github.io
          TOKEN: ${{ secrets.DEPLOY_PAGE }}
          CNAME: jeromepin.fr
